language: python

sudo: required

python:
  - "3.6"
  - "3.7"
  - "3.8"

before_install:
  # install flake8 to perform python code style check in the script part
  # install it using pip in order to get the newest version
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-pip
  - pip install setuptools==60.8.2
  - pip install -U flake8
  - pip install -U pytest 
install:
  - pip install ".[parallel]" .

script:
  - flake8 .
  - pytest .